#!/usr/bin/env bash
# Prints an nginx server block for this instance's .env, ready to drop
# into /etc/nginx/sites-available/ on a machine that already runs other
# services behind nginx. Doesn't touch the host's nginx config itself -
# review and install it yourself (see the printed instructions).
#
# Why the extra `location ~ ^/(...)` block: a few paths in this image
# (/auth/publish, /internal/control/record/start, /recordings) are meant
# to be reachable only from 127.0.0.1 *inside the container*. Once a
# host-level reverse proxy forwards to the container over 127.0.0.1, the
# container can't tell a proxied internet request apart from a real
# loopback one - so those paths have to be blocked here, at the proxy,
# instead.
set -euo pipefail
cd "$(dirname "$0")"

ENV_FILE=.env
[ -f "$ENV_FILE" ] || { echo "no .env - run ./setup.sh first" >&2; exit 1; }
set -a && source "$ENV_FILE" && set +a

: "${DOMAIN:?DOMAIN not set in .env}"
: "${HTTP_PORT:=8080}"

cat <<EOF
# --- $DOMAIN --------------------------------------------------------
# generated by nginx-vhost.sh from $ENV_FILE - re-run after changing
# DOMAIN or HTTP_PORT to regenerate.
server {
    listen 80;
    server_name $DOMAIN;

    location ~ ^/(auth/publish|internal/control/record/start|recordings) {
        return 403;
    }

    location / {
        proxy_pass http://127.0.0.1:$HTTP_PORT;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
EOF

echo "# --- install -----------------------------------------------------" >&2
echo "# ./nginx-vhost.sh | sudo tee /etc/nginx/sites-available/$DOMAIN.conf" >&2
echo "# sudo ln -s /etc/nginx/sites-available/$DOMAIN.conf /etc/nginx/sites-enabled/" >&2
echo "# sudo nginx -t && sudo systemctl reload nginx" >&2
echo "# sudo certbot --nginx -d $DOMAIN     # or your usual TLS flow" >&2
echo "# sudo ufw allow ${RTMP_PORT:-1935}/tcp   # RTMP bypasses nginx entirely" >&2
